### ISSUE TITLE
generation of adversarial examples for other modelexcept inception_v3 using SI-NI-FGSM

### ISSUE THREAD

**Issue by jdg900** [JHL-HUST/SI-NI-FGSM#2]

**Comment by jdg900** [comment]
Hi. 
I have a question about si_ni_fgsm.py

To generate adversarial examples for other models like resnet_v2, inception_v4, etc, do I need to define a new graph for that models? 

there exists only a graph for inception_v3 in si_ni_fgsm.py


Thank you

**Comment by lin2020** [comment]
Yes, you should define a new graph by changing
https://github.com/JHL-HUST/SI-NI-FGSM/blob/e3887d3e8a0197961badbb6cf48ac5d0062989ab/mi_fgsm.py#L146
and than load the corresponding model parameters by changing
https://github.com/JHL-HUST/SI-NI-FGSM/blob/e3887d3e8a0197961badbb6cf48ac5d0062989ab/mi_fgsm.py#L234
and
https://github.com/JHL-HUST/SI-NI-FGSM/blob/e3887d3e8a0197961badbb6cf48ac5d0062989ab/mi_fgsm.py#L244

**Comment by jdg900** [comment]
Ahh, I see.

I appreciate your reply.

Thank you!
