### ISSUE TITLE
Ensemble attack

### ISSUE THREAD

**Issue by SanghyeokSon** [JHL-HUST/SI-NI-FGSM#3]
Thank you for sharing your nice work!

I have a question about ensemble attack.
Is there any code to run an ensemble attack? I can't find the ensemble in your codes.

**Comment by lin2020** [comment]
Hi, I have uploaded a code to show how to run an ensemble attack. Please see [ni_fgsm_ens.py.](https://github.com/JHL-HUST/SI-NI-FGSM/blob/master/ni_fgsm_ens.py)

**Comment by SanghyeokSon** [comment]
I appreciate it :)
