### ISSUE TITLE
Attacking defense model

### ISSUE THREAD

**Issue by jdg900** [JHL-HUST/SI-NI-FGSM#4]
Hi. 

I'm impressed with your paper.

I have some questions about attacking the advanced defense model in your paper.

1. When measuring the performance of the defense model, did you attack with Ensemble AE samples already made?

2. When I look at the githubs of defense methods, there are several target model(ex mobilenet, inceptionnet, etc) to measure the performance., and the code of dataloader is limited to MNIST and CIFAR10.  How did you decide that?

I'd be grateful if you answer me

Thank you!

**Comment by lin2020** [comment]
Hi. Thanks for your attention on our work.
1. Yes.
2. General, we use the target model provided by the defense method to measure the performance. If they not provide pretrained model on ImageNet, you can train by yourself or just compare the results of MNIST and CIFAR10.

**Comment by jdg900** [comment]
Thank you!
